name: "Build NetHunter Kernel gta4xl"

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    name: "🐎 Build kernel"
    runs-on: ubuntu-latest
    
    steps:
      - name: "😄 Checkout"
        uses: actions/checkout@v4

      - name: "⭐ Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc curl git zip gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev zstd wget libfl-dev python3 libarchive-tools jq

      - name: "🌟 Clone Source & Toolchain"
        run: |
          REPO=$(jq -r '.[0].kernelSource.repo' repos.json)
          BRANCH=$(jq -r '.[0].kernelSource.branch' repos.json)
          git clone --depth=1 -b $BRANCH $REPO source
          # Используем проверенный GCC для Android ядер
          git clone --depth=1 https://github.com/mvaisakh/gcc-arm64 toolchain
          echo "$(pwd)/toolchain/bin" >> $GITHUB_PATH

      - name: "👍 Make defconfig"
        run: |
          DEVICE=$(jq -r '.[0].kernelSource.device' repos.json)
          cd source
          make O=../out ARCH=arm64 CROSS_COMPILE=aarch64-elf- ${DEVICE}_defconfig

      - name: "🏴‍☠️ NetHunter Wireless Patch"
        run: |
          cd out
          echo "CONFIG_WIRELESS=y" >> .config
          echo "CONFIG_CFG80211=y" >> .config
          echo "CONFIG_MAC80211=y" >> .config
          echo "CONFIG_CFG80211_WEXT=y" >> .config
          echo "CONFIG_MAC80211_RC_MINSTREL=y" >> .config
          echo "CONFIG_MAC80211_RC_MINSTREL_HT=y" >> .config
          echo "CONFIG_MAC80211_RC_DEFAULT_MINSTREL=y" >> .config
          echo "CONFIG_ATH_COMMON=y" >> .config
          echo "CONFIG_ATH9K_HW=y" >> .config
          echo "CONFIG_ATH9K_COMMON=y" >> .config
          echo "CONFIG_ATH9K_HTC=y" >> .config
          echo "CONFIG_ATH9K_HTC_DEBUGFS=y" >> .config
          echo "CONFIG_RT2X00=y" >> .config
          echo "CONFIG_RT2800USB=y" >> .config

      - name: "🎶 Build kernel"
        run: |
          cd source
          # Добавляем принудительный линкер и эмуляцию для фикса VDSO
          make O=../out ARCH=arm64 CROSS_COMPILE=aarch64-elf- olddefconfig
          make -j$(nproc --all) O=../out ARCH=arm64 CROSS_COMPILE=aarch64-elf- \
          LD=aarch64-elf-ld.bfd \
          LD_LIBRARY_PATH=$(pwd)/../toolchain/lib \
          KBUILD_LDFLAGS_MODULE="--emulation=aarch64elf" \
          VDSO_LDFLAGS="-m aarch64elf"

      - name: "💙 Upload Image.gz"
        uses: actions/upload-artifact@v4
        with:
          name: NetHunter-Kernel-gta4xl
          path: out/arch/arm64/boot/Image.gz
