name: "Build kernels"

env:
  CONFIGURATION: "repos.json"
  OUT_DIR: "out"

on:
  workflow_dispatch:

jobs:
  Set-repos:
    name: "🐂 Parse repos.json"
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.generate-matrix.outputs.repos }}
    steps:
      - name: "😄 Checkout"
        uses: actions/checkout@v4
      - name: "Print repos.json"
        run: cat ${{ env.CONFIGURATION }}
      - name: "😆 Generate Matrix"
        id: generate-matrix
        run: |
          echo "repos=$(jq -c . < ${{ env.CONFIGURATION }})" >> $GITHUB_OUTPUT

  Build-Kernel:
    name: "🐎 Build kernel"
    runs-on: ubuntu-latest
    needs:
      - Set-repos
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        repos: ${{ fromJSON(needs.Set-repos.outputs.repos) }}
    env:
      kernelDir: ${{ matrix.repos.kernelSource.name }}_${{ matrix.repos.kernelSource.device }}
      kernelName: ${{ matrix.repos.kernelSource.name }}
      kernelRepo: ${{ matrix.repos.kernelSource.repo }}
      kernelBranch: ${{ matrix.repos.kernelSource.branch }}
      kernelDevice: ${{ matrix.repos.kernelSource.device }}
      # Имя defconfig можно задать явно, иначе формируется по шаблону <устройство>_defconfig
      DEFCONFIG_NAME: ${{ matrix.repos.kernelSource.defconfig || format('{0}_defconfig', matrix.repos.kernelSource.device) }}
      withKernelSU: ${{ matrix.repos.withKernelSU }}

    steps:
      - name: "✨ Create working dir"
        run: mkdir -p ${{ env.kernelDir }}

      - name: "⭐ Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc curl git zip \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev \
            lftp zstd wget libfl-dev python3 libarchive-tools jq

      - name: "🌟 Clone kernel source"
        working-directory: ./${{ env.kernelDir }}
        run: |
          git clone --recursive --branch ${{ env.kernelBranch }} ${{ env.kernelRepo }} ${{ env.kernelName }} --depth=1

      - name: "💫 Get toolchains"
        working-directory: ./${{ env.kernelDir }}
        env:
          toolchains: "${{ toJSON(matrix.repos.toolchains) }}"
        run: |
          toolchains_num="$(echo $toolchains | jq 'length')"
          for ((i=0;i<toolchains_num;i++)); do
            name=$(echo $toolchains | jq -r ".[$i].name")
            repo=$(echo $toolchains | jq -r ".[$i].repo")
            branch=$(echo $toolchains | jq -r ".[$i].branch")
            git clone --recursive --branch $branch $repo $name --depth=1
            echo "$(pwd)/$name/bin" >> $GITHUB_PATH
          done

      - name: "😎 Set args"
        id: generate-args
        working-directory: ./${{ env.kernelDir }}
        env:
          params: "${{ toJSON(matrix.repos.params) }}"
        run: |
          ARCH=$(echo $params | jq -r ".ARCH")
          CROSS_COMPILE=$(echo $params | jq -r ".CROSS_COMPILE")
          echo "ARCH=$ARCH" >> $GITHUB_ENV
          args="-j$(nproc --all) ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE"
          if [ -n "$OUT_DIR" ]; then
            mkdir -p "$(pwd)/$OUT_DIR"
            args="$args O=$(pwd)/$OUT_DIR"
          fi
          echo "args=$args" >> $GITHUB_OUTPUT

      - name: "😋 Update KernelSU"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        if: ${{ env.withKernelSU == 'true' }}
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main

      - name: "🛠️ Make defconfig"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        env:
          args: ${{ steps.generate-args.outputs.args }}
        run: |
          echo "⚙️  Используем defconfig: ${{ env.DEFCONFIG_NAME }}"
          make ${{ env.args }} ${{ env.DEFCONFIG_NAME }}

      - name: "🏴‍☠️ Inject NetHunter Patches"
        env:
          args: ${{ steps.generate-args.outputs.args }}
        working-directory: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}
        run: |
          echo "Force enabling Wi-Fi drivers..."
          echo "CONFIG_WIRELESS=y" >> .config
          echo "CONFIG_CFG80211=y" >> .config
          echo "CONFIG_MAC80211=y" >> .config
          echo "CONFIG_CFG80211_WEXT=y" >> .config
          echo "CONFIG_MAC80211_RC_DEFAULT_MINSTREL=y" >> .config
          echo "CONFIG_ATH_COMMON=y" >> .config
          echo "CONFIG_ATH9K_HTC=y" >> .config
          echo "CONFIG_RT2X00=y" >> .config
          echo "CONFIG_RT2800USB=y" >> .config
          
          echo "Fixing Stack Protector Error..."
          echo "CONFIG_CC_STACKPROTECTOR_NONE=y" >> .config
          sed -i 's/CONFIG_CC_STACKPROTECTOR_STRONG=y/# CONFIG_CC_STACKPROTECTOR_STRONG is not set/g' .config
          
          echo "Disabling BadUSB / HID gadget..."
          echo "# CONFIG_USB_G_HID is not set" >> .config
          echo "# CONFIG_USB_CONFIGFS_F_HID is not set" >> .config
          
          cd ../${{ env.kernelName }}
          make ${{ env.args }} olddefconfig

      - name: "🎶 Build kernel"
        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
        env:
          args: ${{ steps.generate-args.outputs.args }}
        run: |
          make ${{ env.args }} KCFLAGS="-Wno-error" KBUILD_BUILD_USER="Nursultan" KBUILD_BUILD_HOST="NetHunter"

      - name: "💙 Upload Image.gz"
        uses: actions/upload-artifact@v4
        with:
          name: NetHunter-Kernel-${{ env.kernelDevice }}
          path: ./${{ env.kernelDir }}/${{ env.OUT_DIR }}/arch/${{ env.ARCH }}/boot/Image.gz
          if-no-files-found: ignore
